kafka:
  brokers:
    - "localhost:9092"
  topics:
    chat_messages: "chat-messages"
    chat_responses: "chat-responses"
    agent_input: "agent-input"
    agent_output: "agent-output"

web:
  host: "localhost"
  port: "8080"

agents:
  provider: "ollama"  # "ollama" or "openai"
  model: "llama2"     # Model name (e.g., llama2, codellama, mistral)
  ollama_url: "http://localhost:11434"
  llm_api_key: ""     # Set via LLM_API_KEY environment variable
  llm_url: "https://api.openai.com/v1/chat/completions"
  
  # Natural conversation agents configuration
  natural_agents:
    - id: "curious-agent"
      name: "Curious Agent"
      personality: "curious"
      interests:
        - "questions"
        - "learning"
        - "discovery"
        - "science"
        - "philosophy"
      response_chance: 0.8
      enabled: true
      description: "An inquisitive agent that loves asking questions and learning new things"
      
    - id: "helpful-agent"
      name: "Helpful Agent"
      personality: "helpful"
      interests:
        - "help"
        - "support"
        - "guidance"
        - "problem-solving"
        - "assistance"
      response_chance: 0.9
      enabled: true
      description: "A supportive agent focused on helping others and solving problems"
      
    - id: "technical-agent"
      name: "Technical Agent"
      personality: "technical"
      interests:
        - "programming"
        - "technology"
        - "software"
        - "engineering"
        - "code"
      response_chance: 0.7
      enabled: true
      description: "An engineering-minded agent focused on technical aspects and solutions"
      
    - id: "philosophical-agent"
      name: "Philosophical Agent"
      personality: "philosophical"
      interests:
        - "philosophy"
        - "meaning"
        - "existence"
        - "truth"
        - "reality"
        - "ethics"
      response_chance: 0.6
      enabled: true
      description: "A deep-thinking agent that explores philosophical questions and meanings"